/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fbf9f5',
        'surface-dim': '#dbdad6',
        'surface-bright': '#fbf9f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3ef',
        'surface-container': '#efeeea',
        'surface-container-high': '#eae8e4',
        'surface-container-highest': '#e4e2de',
        'on-surface': '#1b1c1a',
        'on-surface-variant': '#404944',
        'inverse-surface': '#30312e',
        'inverse-on-surface': '#f2f0ed',
        outline: '#707974',
        'outline-variant': '#bfc9c3',
        'surface-tint': '#2b6954',
        primary: '#003527',
        'on-primary': '#ffffff',
        'primary-container': '#064e3b',
        'on-primary-container': '#80bea6',
        'inverse-primary': '#95d3ba',
        secondary: '#735c00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed65b',
        'on-secondary-container': '#745c00',
        tertiary: '#531e00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#72310b',
        'on-tertiary-container': '#f89a6c',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#b0f0d6',
        'primary-fixed-dim': '#95d3ba',
        'on-primary-fixed': '#002117',
        'on-primary-fixed-variant': '#0b513d',
        'secondary-fixed': '#ffe088',
        'secondary-fixed-dim': '#e9c349',
        'on-secondary-fixed': '#241a00',
        'on-secondary-fixed-variant': '#574500',
        'tertiary-fixed': '#ffdbcc',
        'tertiary-fixed-dim': '#ffb693',
        'on-tertiary-fixed': '#351000',
        'on-tertiary-fixed-variant': '#76330d',
        background: '#fbf9f5',
        'on-background': '#1b1c1a',
        'surface-variant': '#e4e2de',
        gold: '#d4af37',
        emerald: '#064e3b',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'serif'],
        body: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['30px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.7', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'container-max': '1280px',
        gutter: '24px',
        unit: '8px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      boxShadow: {
        ambient: '0 20px 50px -12px rgba(6, 78, 59, 0.04)',
      },
    },
  },
  plugins: [],
}